info:
  app:
    name: "Submissões de Artigos"
    description: "Projeto para submissões de artigos científicos em evento"
    version: "0.0.1.SNAPSHOT"

spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:file:~/db/Submissao"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
#  http:
#      multipart:
#        max-file-size: 20MB
#        max-request-size: 20MB

submissao:
  uploadFilePath: "/tmp/submissao/files"

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "health, env, metrics, sessions, mappings, info, liquibase"
